# Generated by Django 5.2.1 on 2025-05-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True, help_text="Comma-separated topics you're interested in"),
        ),
    ]
