# Generated by Django 5.0.3 on 2025-05-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_housingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='housinglisting',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
